// Generated by CoffeeScript 1.7.1
"use strict";
var app, config, exports, express, http, io, server, session, socket;

express = require("express");

session = require('./lib/session');


/*
Main application file
 */

process.env.NODE_ENV = process.env.NODE_ENV || "development";

config = require("./lib/config/config");

app = express();

http = require("http");

server = http.createServer(app);

socket = require("./lib/socket.js");

io = require("socket.io").listen(server);

require('./lib/passport').socket(io);

io.sockets.on("connection", socket);

require("./lib/config/express")(app);

require("./lib/routes")(app);

server.listen(config.port, function() {
  console.log("Express server listening on port %d in %s mode", config.port, app.get("env"));
});

exports = module.exports = app;
