// Generated by CoffeeScript 1.7.1
'use strict';
var Promise, model, p, p1, p2, pl, props, pros, _i, _len;

model = require('../../../lib/model');

Promise = require('bluebird');

p1 = model.player.get({
  id: '774b7a8a-c228-4cb1-8d54-268cacf78014',
  io: 'socket.id'
});

p2 = model.player.get({
  id: '03164946-3d58-461d-bb15-a9e09f050964',
  io: 'socket.id'
});

pl = [p2, p1, p1, p2];

pros = (function() {
  var _i, _len, _results;
  _results = [];
  for (_i = 0, _len = pl.length; _i < _len; _i++) {
    p = pl[_i];
    _results.push(model.user.id(p.id));
  }
  return _results;
})();

props = {};

for (_i = 0, _len = pl.length; _i < _len; _i++) {
  p = pl[_i];
  props[p.id] = model.user.id(p.id);
}

Promise.props(props).then(function(r) {
  return console.log(r);
});
