// Generated by CoffeeScript 1.7.1
'use strict';
var model;

model = require('../../../lib/model');

model.user.find('张三').then(function(profile) {
  return console.log(profile);
}, function(err) {
  return console.log(err);
});

model.user.find('邓娟').then(function(profile) {
  console.log(profile);
  return model.user.id(profile.id).then(function(profile) {
    return console.log(profile);
  });
}, function(err) {
  return console.log(err);
});
