// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('myNewProjectApp').controller('MainCtrl', function($scope, $http, $location) {
  $scope.username = '罗涛';
  $scope.login = function() {
    return $http.post('/login', {
      name: $scope.username
    }).success(function(res) {
      var err, token;
      err = res[0], token = res[1];
      if (err) {
        return console.log(err);
      }
      console.log(token);
      return $location.path('/wis');
    }).error(function(err) {
      return console.log(err);
    });
  };
  $scope.isSpecificPage = function() {
    return false;
  };
});
