// Generated by CoffeeScript 1.7.1
'use strict';
app.controller('WisCtrl', [
  '$scope', 'socket', function($scope, socket) {
    var context;
    $scope.title = 'Room';
    context = {
      user: {
        id: 1,
        name: 'lot'
      },
      room: {
        id: 'tuhao',
        name: '我的土豪朋友们'
      }
    };
    socket.emit('room:enter', context, function(msg) {
      return $scope.title = msg;
    });
    return socket.on('room:join', function(data) {
      return console.log(data);
    });
  }
]);
