// Generated by CoffeeScript 1.7.1
'use strict';
app.controller('WisCtrl', [
  '$scope', 'socket', function($scope, socket) {
    $scope.title = 'Room';
    socket.emit('room:enter', {}, function(profile) {
      return console.log(profile);
    });
    socket.on('room:enter', function(msg) {
      return console.log(msg);
    });
    return socket.on('room:join', function(data) {
      console.log(data);
      return $scope.players = data;
    });
  }
]);
