// Generated by CoffeeScript 1.7.1
'use strict';
var Promise, uuid, _;

uuid = require('node-uuid').v4;

Promise = require('bluebird');

_ = require('lodash');

module.exports = function(client) {
  var add, player, players, remove;
  player = require('./player')(client);
  players = [];
  remove = function(io) {
    return _.remove(players, function(p) {
      return p.id === io.id;
    });
  };
  add = function(io) {
    _.remove(players, function(p) {
      return p.id === io.id;
    });
    return players.push(player.get(io));
  };
  return {
    add: add,
    remove: remove,
    status: function() {
      return players;
    }
  };
};
