// Generated by CoffeeScript 1.7.1
'use strict';
var Promise, model, uuid, _;

uuid = require('node-uuid').v4;

Promise = require('bluebird');

_ = require('lodash');

model = require('./index');

module.exports = function(client) {
  var add, players, remove;
  players = [];
  remove = function(io) {
    return _.remove(players, function(p) {
      return p.uid === io.uid;
    });
  };
  add = function(io) {
    _.remove(players, function(p) {
      return p.uid === io.uid;
    });
    return players.push(io);
  };
  return {
    add: add,
    remove: remove,
    status: function() {
      return players;
    }
  };
};
