// Generated by CoffeeScript 1.7.1
'use strict';
module.exports = function(client) {
  var Player, user;
  user = require('./user')(client);
  Player = (function() {
    function Player(options) {
      this.id = options.id;
      this.io = options.io;
      user.id(this.id).bind(this).then(function(user) {
        this.profile = user.profile;
      });
    }

    return Player;

  })();
  return {
    get: function(options) {
      return new Player(options);
    }
  };
};
