// Generated by CoffeeScript 1.7.1
'use strict';
var Model, api, game, index, passport;

api = require('./controllers/api');

index = require('./controllers');

passport = require('./passport');

Model = require('./model');

game = require('./game');


/*
Application routes
 */

module.exports = function(app) {
  app.get('/status', function(req, res) {
    return res.json(Model.game.status());
  });
  app.post('/login', function(req, res) {
    return passport.login(req.body.name).then(function(token) {
      req.session.token = token;
      return res.json([
        null, {
          token: token
        }
      ]);
    }, function(err) {
      req.session.token = null;
      return res.json([err]);
    });
  });
  app.get('/api/awesomeThings', api.awesomeThings);
  app.get('/api/*', function(req, res) {
    res.send(404);
  });
  app.get('/partials/*', index.partials);
  app.get('/*', index.index);
};
