// Generated by CoffeeScript 1.7.1
var MemoryStore, RedisStore, express, session;

express = require('express');

session = require('express-session');

RedisStore = require('connect-redis')(session);

MemoryStore = express.session.MemoryStore;

module.exports = (function() {
  var COOKIE_SECRET, cookieParser, sessionStore;
  COOKIE_SECRET = 'my secret cookie';
  cookieParser = express.cookieParser(COOKIE_SECRET);
  sessionStore = new RedisStore();
  return {
    sessionStore: sessionStore,
    secret: 'SEKR319',
    key: 'sid',
    cookieSecret: COOKIE_SECRET,
    cookieParser: cookieParser
  };
})();
