// Generated by CoffeeScript 1.7.1
module.exports = function(socket) {
  socket.emit('news', {
    hello: 'world'
  });
  socket.on('my other event', function(data) {
    return console.log(data);
  });
  return socket.on('echo', function(msg) {
    console.log(msg);
    return socket.emit('echo', msg);
  });
};
