// Generated by CoffeeScript 1.7.1
var game, model, passport;

passport = require('./passport');

game = require('./game');

model = require('./model');

module.exports = function(socket) {
  var context, sid, sss, uid;
  sid = socket.handshake.sessionID;
  uid = socket.handshake.uid;
  sss = {
    id: uid,
    io: socket.id
  };
  model.game.add(sss);
  console.log('A socket with UID ' + uid + ' connected!');
  socket.on('disconnect', function() {
    console.log('A socket with UID ' + uid + ' disconnected!');
    model.game.remove(sss);
    socket.emit('room:join', model.game.status());
    return socket.broadcast.emit('room:join', model.game.status());
  });
  context = {
    uid: uid,
    sid: sid,
    io: socket.id
  };
  game.GameManager.register(context);
  socket.on('room:enter', function(cxt, fn) {});
  socket.emit('room:join', model.game.status());
  socket.broadcast.emit('room:join', model.game.status());
  return socket.on('echo', function(msg) {
    console.log(msg);
    return socket.emit('echo', msg);
  });
};
