// Generated by CoffeeScript 1.7.1
module.exports = function(socket) {
  var game;
  game = require('./game').Game;
  socket.on('room:enter', function(cxt, fn) {
    socket.join(cxt.user.id);
    game.join(game.player(cxt.user.id), game.room(cxt.room.id));
    game.debug();
    return fn(cxt.user.name + ' joined ' + cxt.room.name);
  });
  socket.emit('room:join', {
    hello: 'world'
  });
  socket.emit('news', {
    hello: 'world'
  });
  socket.on('my other event', function(data) {
    return console.log(data);
  });
  return socket.on('echo', function(msg) {
    console.log(msg);
    return socket.emit('echo', msg);
  });
};
