// Generated by CoffeeScript 1.7.1
"use strict";
var path, session;

path = require("path");

session = require("../session");


/*
Send partial, or 404 if it doesn't exist
 */

exports.partials = function(req, res) {
  var requestedView, stripped;
  stripped = req.url.split(".")[0];
  requestedView = path.join("./", stripped);
  res.render(requestedView, function(err, html) {
    if (err) {
      console.log("Error rendering partial '" + requestedView + "'\n", err);
      res.status(404);
      res.send(404);
    } else {
      res.send(html);
    }
  });
};


/*
Send our single page app
 */

exports.index = function(req, res) {
  res.render("index");
};
