// Generated by CoffeeScript 1.7.1
'use strict';
var path, redis, rootPath;

path = require('path');

rootPath = path.normalize(__dirname + '/../../..');

redis = require('redis');

module.exports = {
  root: rootPath,
  port: process.env.PORT || 3000,
  redis: redis.createClient()
};
